### ISSUE TITLE
wrong number of arguments (given 3, expected 1..2)

### ISSUE THREAD

**Issue by szabgab** [simple-and-powerful/act-form#9]
After running `bundle install`  I tried to run the tests with:

```
bundle exec rake
```

And got this exception:

```
opt/lib/act_form/attributes.rb:30:in `attribute': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
	from /opt/lib/act_form/merge.rb:11:in `block in merge_attribute_set_from'
	from /opt/lib/act_form/merge.rb:9:in `each'
	from /opt/lib/act_form/merge.rb:9:in `merge_attribute_set_from'
	from /opt/lib/act_form/combinable.rb:43:in `block in combine'
	from /opt/lib/act_form/combinable.rb:38:in `each'
	from /opt/lib/act_form/combinable.rb:38:in `combine'
	from /opt/test/test_helper.rb:42:in `<class:GlueForm>'
	from /opt/test/test_helper.rb:39:in `<top (required)>'
	from /opt/test/form_model_spec.rb:1:in `require_relative'
	from /opt/test/form_model_spec.rb:1:in `<top (required)>'
	from /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

```
# ruby --version
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) 
```

Should

**Comment by zires** [comment]
The code does have problems in `ruby >= 3.0`.
PR have merged.
